create table pedidos (id_pedido bigint generated by default as identity not null, produtos_id_produto bigint, usuarios_id bigint, primary key (id_pedido));
create table produtos (id_produto bigint generated by default as identity not null, categorias varchar(255), descricao_produto varchar(255) not null, estoque integer, imagem varchar(255) not null, nome_produto varchar(255) not null, valor_produto double precision not null, primary key (id_produto));
create table usuarios (id_usuario bigint generated by default as identity not null, cpf_usuario varchar(11), nome varchar(255), senha varchar(255), usuario varchar(255), primary key (id_usuario));
alter table usuarios add constraint unique_cpf_usuario unique (cpf_usuario);
alter table usuarios add constraint unique_user unique (usuario);
alter table pedidos add constraint fk_pedidos_produto foreign key (produtos_id_produto) references produtos (id_produto);
alter table pedidos add constraint fk_pedidos_usuarios foreign key (usuarios_id) references usuarios (id_usuario);